[dotfiles]
symlinks = [
{ target = "~/.config/fedup/dotfiles/bashrc/.bashrc", link = "~/.bashrc"},
{ target = "~/.config/fedup/dotDesktop/cursor.desktop", link ="~/.local/share/applications/cursor.desktop"},
{ target = "~/.config/pibble/pibble", link = "~/.local/bin/pibble"},
{ target = "~/.config/fedup/dotfiles/matugen", link = "~/.config/matugen"},
{ target = "~/.config/fedup/dotfiles/matugen/matugen-apply.sh", link = "~/.local/bin/matugen-apply"},
{ target = "~/.config/fedup/dotfiles/starship.toml", link = "~/.config/starship.toml"},
]
