[dnf]
install = [
    "bash-completion",
    "brave-origin-nightly",
    "cargo",
    "codium",
    "curl",
    "dnf5-plugins",
    "eza",
    "fzf",
    "gnome-disk-utility",
    "nano",
    "steam",
    "trash-cli",
    "unzip",
    "wl-clipboard",
    "wl-paste",
    "wtype",
    "xclip",
    "xdotool",
    "ydotool",
    "zoxide"
]

[flatpak]
install = [
    "com.github.tchx84.Flatseal",
    "io.github.kolunmi.Bazaar"
]

[pip]
install = [
    "piper-onnx"
]

[npm]
install = [
    "opencode-ai"
]

