# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"

# PATH
export PATH="$HOME/.opencode/bin:$PATH"
export PATH="$HOME/fedup-v0.1.0-linux-x86_64:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"

# Theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Powerlevel10k config (generated by p10k configure wizard)
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# System-installed plugins (Fedora packages)
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh 2>/dev/null
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null

# zsh-syntax-highlighting — vague.nvim palette (256-color approximations)
# https://github.com/vague2k/vague.nvim
typeset -gA ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[default]='fg=251'                # fg        #cdcdcd
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=168,bold'     # error     #d8647e
ZSH_HIGHLIGHT_STYLES[command]='fg=152'                # builtin   #b4d4cf
ZSH_HIGHLIGHT_STYLES[builtin]='fg=152'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=152'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=152'
ZSH_HIGHLIGHT_STYLES[function]='fg=174'               # func      #c48282
ZSH_HIGHLIGHT_STYLES[alias]='fg=174'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=67'           # keyword   #6e94b2
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=60'        # comment   #606079
ZSH_HIGHLIGHT_STYLES[comment]='fg=60'
ZSH_HIGHLIGHT_STYLES[string]='fg=180'                 # string    #e8b589
ZSH_HIGHLIGHT_STYLES[dollar-quoted-escape]='fg=173'   # number    #e0a363
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=146'   # constant  #aeaed1
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=146'
ZSH_HIGHLIGHT_STYLES[path]='fg=189,underline'         # property  #c3c3d5
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=189'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=216'               # warning   #f3be7c
ZSH_HIGHLIGHT_STYLES[variable]='fg=139'               # parameter #bb9dbd
ZSH_HIGHLIGHT_STYLES[named-fd]='fg=139'
ZSH_HIGHLIGHT_STYLES[numeric-fd]='fg=139'

# Autosuggestions in vague comment grey
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=60'

# zoxide — smarter cd (like fish's z)
eval "$(zoxide init zsh)" 2>/dev/null

source $ZSH/oh-my-zsh.sh

# eza — modern ls replacement with git info (after oh-my-zsh so it overrides)
alias ls='eza -la --group-directories-first --icons --git'
alias lt='eza -T --group-directories-first'

# To customize prompt, run: p10k configure

# added by fedup (npm global)
export PATH="$HOME/.npm-global/bin":$PATH

. "$HOME/.local/share/../bin/env"
