-- matugen-generated colors for Hyprland (managed by fedup)
-- Generated by matugen from the current wallpaper; do not edit.
-- Loaded from hyprland.lua via require("colors").
return {
    accent  = "0x{{colors.primary.default.hex_stripped}}",
    accent2 = "0x{{colors.secondary.default.hex_stripped}}",
    hint    = "0x{{colors.tertiary.default.hex_stripped}}",
    fg      = "0x{{colors.on_surface.default.hex_stripped}}",
    muted   = "0x{{colors.outline.default.hex_stripped}}",
    bg      = "0x{{colors.surface.default.hex_stripped}}",
    bg_alt  = "0x{{colors.surface_container.default.hex_stripped}}",
    error   = "0x{{colors.error.default.hex_stripped}}",
    warning = "0x{{colors.tertiary.default.hex_stripped}}",
    success = "0x{{colors.primary.default.hex_stripped}}",
}
